# read config
OUTDIR = config["outdir"]
ASSEMBLY = config["assembly"]
HIFI = config["hifi"]
NANOPORE = config["nanopore"]
PACBIO = config["pacbio"]
FR = config['forward_reads']
RR = config['reverse_reads']
EXECUTION_FOLDER = config['execution_folder']
BAM = config['bam']
MIN_LENGTH = config['min_length_threshold']
MEAN_COVERAGE_FRACTION = config["mean_coverage_fraction"]
MODE = config["mode"]
SPLIT_SCRIPT = config['split_script']
PREFIX = config["prefix"]
ZL_THRESHOLD = config["z_low_threshold"]
ZH_THRESHOLD = config["z_high_threshold"]
TAIL_THRESHOLD = config["tail_length_threshold"]
REMOVE_LOW_COVERAGE = config["remove_low_coverage"]


rule all:
    input:
        f"{OUTDIR}/{PREFIX}_splitted.fa",

rule envs:
    input:
        align = "../envs/align.yaml",
        bedtools = "../envs/bedtools.yaml"

envs = rules.envs.input

if MODE == "bam":
    BAM = BAM

elif MODE == "hifi":
    include: "./rules/align_hifi.smk"
    BAM = rules.get_coverage_hifi.output.alignment_bam

elif MODE == "nanopore":
    include: "./rules/align_nanopore.smk"
    BAM = rules.get_coverage_nanopore.output.alignment_bam

elif MODE == "pacbio":
    include: "./rules/align_pacbio.smk"
    BAM = rules.get_coverage_pacbio.output.alignment_bam

elif MODE == "paired":
    include: "./rules/align_paired.smk"
    BAM = rules.get_coverage_paired.output.alignment_bam

include: "./rules/get_coverage.smk"

include: "./rules/split_by_coverage.smk"